### ISSUE TITLE
Ability to add parameters to route in menu

### ISSUE THREAD

**Issue by Albvadi** [HZ-HBO-ICT/Laravel-CoreUI#34]
Hi,
first of all, thanks for this awesome package. It´s really usefull for a quick base in new developments.

Sometimes, the menu items need to point a route with params (not always index views), and with the package isn´t possible to add the parameters to route.

Reviewing the menu builder, in the UrlGenerator, is generating like this `$this->urlGenerator->route($item['route']);` so should work:
```php
[
    'route' => ['user.edit', ['1']] // <-- 1 is index of the user for example, 
]
```

thus defining the route in the coreui config, crash the app with an `Illegal offset type`.

![image](https://user-images.githubusercontent.com/6285255/66380733-486f0380-e9b8-11e9-8b93-6af2007b4641.png)

Thank you!

**Comment by Lucky-Loek** [comment]
Thanks for using and liking the package!

The error you're running into is a design choice. We consider it bad practice to hard-code an identifier into a static menu. There is a fairly easy way to add it in a dynamic way though, by levering the `BuildingMenu` event in one of your ServiceProviders:

```php
use Illuminate\Events\Dispatcher;
use HzHboIct\LaravelCoreUI\Events\BuildingMenu;

class AppServiceProvider extends ServiceProvider
{

    public function boot(Dispatcher $events)
    {
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add([
                'text' => 'Edit user',
                'url' => route('user.edit', 1),
            ]);
        });
    }

}
```

Note though, that this pushes the item to the bottom of your menu pane. So it might be a good choice to define your entire menu in `$event->menu->add()` functions. This might even be a better idea since the menu will only be built when its needs to be, instead of on every request that hits your application 😄 

Hope this helps!

**Comment by Albvadi** [comment]
> The error you're running into is a design choice. We consider it bad practice to hard-code an identifier into a static menu.

I understand the point of view, maybe it's a bad practice, but sometimes it´s a must. The identifier was only an example, I needed to pass a `$var` with a ViewComposer for example.

Other example, if you need include a badge in the menu (with a notification number or a "NEW" badge to get the attention of the user, like the CoreUI Live Preview). The menu remains static, but you need dynamics components.

![image](https://user-images.githubusercontent.com/6285255/66388035-9807fc00-e9c5-11e9-9a88-3b1f6f506c48.png)

Anyway, although I think it is worse practice to define a complete menu in the ServiceProvider when you have a section in for the menu in the configuration file, the alternative you have given me is very helpful. I will take a look to see how I can do what I need.

Feel free to close this issue if you don´t plan to evaluate making changes to the menu builder.

Again, thanks so much for this package and for your quick reply!! Much appreciated... :blush:

**Comment by Lucky-Loek** [comment]
Since we're a school, the principal aim of this package is to make life a little easier for our freshman year students. I get where you're coming from, but we'll probably not add functionality like this unless our students start asking about it. Usually, they don't need stuff like this because it's already hard enough to create a decent app that actually runs without errors 😋 

Though badges should be fairly easy to implement... Can you make an issue with a feature request for that? If I find some time this week, I will add that.

I think `badge-text`, `badge-context` (`'primary'`, `'danger'`, etc) and `badge-pill` (`true`, `false`) would do it?
